#!/usr/bin/env node

/**
 * Generate GA4 gtag.js tracking code based on the event spec.
 * Outputs a ready-to-paste HTML snippet and a JS helper module.
 *
 * Usage: node scripts/generate-gtag.mjs --measurement-id G-XXXXXXXXXX [--output output/]
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const currentDir = dirname(fileURLToPath(import.meta.url));

function parseArgs() {
  const args = process.argv.slice(2);
  const options = { measurementId: null, output: resolve(currentDir, '../output') };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--measurement-id' && args[i + 1]) {
      options.measurementId = args[++i];
    } else if (args[i] === '--output' && args[i + 1]) {
      options.output = resolve(args[++i]);
    }
  }
  return options;
}

const EVENTS = [
  { name: 'sign_up', params: ['method'], description: 'User completed registration' },
  { name: 'onboarding_complete', params: ['steps_completed', 'time_seconds'], description: 'User finished onboarding flow' },
  { name: 'first_value_delivered', params: ['feature_name', 'time_to_value_seconds'], description: 'User received core product value for the first time' },
  { name: 'feature_used', params: ['feature_name', 'usage_count'], description: 'User used a core feature' },
  { name: 'content_generated', params: ['content_type', 'quality_score'], description: 'User generated or received an output' },
  { name: 'share', params: ['method', 'content_type'], description: 'User shared content' },
  { name: 'feedback_submitted', params: ['rating', 'feedback_type'], description: 'User submitted feedback or rating' },
  { name: 'pricing_page_view', params: ['source_page'], description: 'User viewed the pricing page' },
  { name: 'checkout_start', params: ['plan_name', 'price', 'currency'], description: 'User started the payment flow' },
  { name: 'purchase', params: ['transaction_id', 'plan_name', 'value', 'currency'], description: 'Payment completed' },
  { name: 'subscription_renewed', params: ['plan_name', 'period', 'value'], description: 'Subscription renewed' },
  { name: 'refund', params: ['transaction_id', 'reason'], description: 'Refund processed' },
  { name: 'return_visit', params: ['days_since_last_visit'], description: 'Non-first visit after 24h+ gap' },
  { name: 'landing_page_view', params: ['page_variant', 'keyword', 'country', 'language'], description: 'Landing page loaded' },
];

function generateHtmlSnippet(measurementId) {
  return `<!-- Google Analytics 4 - Paste in <head> -->
<script async src="https://www.googletagmanager.com/gtag/js?id=${measurementId}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '${measurementId}');
</script>`;
}

function generateHelperModule(measurementId) {
  const eventFunctions = EVENTS.map((event) => {
    const paramList = event.params.map((p) => `${p}`).join(', ');
    const paramObject = event.params.map((p) => `    ${p}`).join(',\n');
    return `/**
 * ${event.description}
 */
export function track${toPascalCase(event.name)}(${paramList}) {
  gtag('event', '${event.name}', {
${paramObject}
  });
}`;
  }).join('\n\n');

  return `/**
 * GA4 Tracking Helpers
 * Measurement ID: ${measurementId}
 * Generated by startup-playbook google-growth-stack
 *
 * Import this module and call the tracking functions.
 * Requires gtag.js snippet loaded in the page <head>.
 */

/* global gtag */

// User properties — call once after login or profile load
export function setUserProperties({ userPlan, userSignupDate, userCountry, userLanguage }) {
  gtag('set', 'user_properties', {
    user_plan: userPlan,
    user_signup_date: userSignupDate,
    user_country: userCountry,
    user_language: userLanguage,
  });
}

${eventFunctions}
`;
}

function toPascalCase(snakeStr) {
  return snakeStr
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function main() {
  const options = parseArgs();
  if (!options.measurementId) {
    console.error('Usage: node scripts/generate-gtag.mjs --measurement-id G-XXXXXXXXXX [--output output/]');
    process.exit(1);
  }

  mkdirSync(options.output, { recursive: true });

  const htmlPath = resolve(options.output, 'gtag-snippet.html');
  const jsPath = resolve(options.output, 'ga4-tracking.mjs');

  writeFileSync(htmlPath, generateHtmlSnippet(options.measurementId), 'utf-8');
  writeFileSync(jsPath, generateHelperModule(options.measurementId), 'utf-8');

  console.log(`\n✅ GA4 tracking code generated:\n`);
  console.log(`   HTML snippet: ${htmlPath}`);
  console.log(`   JS helpers:   ${jsPath}`);
  console.log(`\n   Measurement ID: ${options.measurementId}`);
  console.log(`   Events defined: ${EVENTS.length}`);
  console.log(`\n📋 Next steps:`);
  console.log(`   1. Paste the HTML snippet into your page <head>.`);
  console.log(`   2. Import ga4-tracking.mjs and call tracking functions.`);
  console.log(`   3. Open GA4 DebugView to verify events fire correctly.\n`);
}

main();
